// Add user
export const CREATE_USER_FETCHING = 'CREATE_USER_FETCHING'
export const CREATE_USER_FETCH = 'CREATE_USER_FETCH'
export const CREATE_USER_FETCH_ERROR = 'CREATE_USER_FETCH_ERROR'
// Delete user
export const DELETE_USER_FETCHING = 'DELETE_USER_FETCHING'
export const DELETE_USER_FETCH = 'DELETE_USER_FETCH'
export const DELETE_USER_FETCH_ERROR = 'DELETE_USER_FETCH_ERROR'
// Update user
export const EDIT_USER_FETCHING = 'EDIT_USER_FETCHING'
export const EDIT_USER_FETCH = 'EDIT_USER_FETCH'
export const EDIT_USER_FETCH_ERROR = 'EDIT_USER_FETCH_ERROR'
//Get user
export const GET_USER_FETCHING = 'GET_USER_FETCHING'
export const GET_USER_FETCH = 'GET_USER_FETCH'
export const GET_USER_FETCH_ERROR = 'GET_USER_FETCH_ERROR'
//Get users
export const GET_USERS_FETCHING = 'GET_USERS_FETCHING'
export const GET_USERS_FETCH = 'GET_USERS_FETCH'
export const GET_USERS_FETCH_ERROR = 'GET_USERS_FETCH_ERROR'
