//Get survey
export const GET_SURVEY_FETCHING = 'GET_SURVEY_FETCHING'
export const GET_SURVEY_FETCH = 'GET_SURVEY_FETCH'
export const GET_SURVEY_FETCH_ERROR = 'GET_SURVEY_FETCH_ERROR'
//Get surveys
export const GET_SURVEYS_FETCHING = 'GET_SURVEYS_FETCHING'
export const GET_SURVEYS_FETCH = 'GET_SURVEYS_FETCH'
export const GET_SURVEYS_FETCH_ERROR = 'GET_SURVEYS_FETCH_ERROR'
//Get sellers
export const GET_SELLERS_FETCHING = 'GET_SELLERS_FETCHING'
export const GET_SELLERS_FETCH = 'GET_SELLERS_FETCH'
export const GET_SELLERS_FETCH_ERROR = 'GET_SELLERS_FETCH_ERROR'
//Get clients
export const GET_CLIENTS_FETCHING = 'GET_CLIENTS_FETCHING'
export const GET_CLIENTS_FETCH = 'GET_CLIENTS_FETCH'
export const GET_CLIENTS_FETCH_ERROR = 'GET_CLIENTS_FETCH_ERROR'
// Get surveysInitialCall
export const GET_SURVEY_INITIAL_CALL_FETCH = 'GET_SURVEY_INITIAL_CALL_FETCH'
