// Add BOT_TRAINING
export const CREATE_BOT_TRAINING_FETCHING = "CREATE_BOT_TRAINING_FETCHING"
export const CREATE_BOT_TRAINING_FETCH = "CREATE_BOT_TRAINING_FETCH"
export const CREATE_BOT_TRAINING_FETCH_ERROR = "CREATE_BOT_TRAINING_FETCH_ERROR"
// Delete BOT_TRAINING
export const DELETE_BOT_TRAINING_FETCHING = "DELETE_BOT_TRAINING_FETCHING"
export const DELETE_BOT_TRAINING_FETCH = "DELETE_BOT_TRAINING_FETCH"
export const DELETE_BOT_TRAINING_FETCH_ERROR = "DELETE_BOT_TRAINING_FETCH_ERROR"
// Update BOT_TRAINING
export const EDIT_BOT_TRAINING_FETCHING = "EDIT_BOT_TRAINING_FETCHING"
export const EDIT_BOT_TRAINING_FETCH = "EDIT_BOT_TRAINING_FETCH"
export const EDIT_BOT_TRAINING_FETCH_ERROR = "EDIT_BOT_TRAINING_FETCH_ERROR"
//Get BOT_TRAINING
export const GET_BOT_TRAINING_FETCHING = "GET_BOT_TRAINING_FETCHING"
export const GET_BOT_TRAINING_FETCH = "GET_BOT_TRAINING_FETCH"
export const GET_BOT_TRAINING_FETCH_ERROR = "GET_BOT_TRAINING_FETCH_ERROR"
//Get BOT_TRAININGs
export const GET_BOT_TRAININGS_FETCHING = "GET_BOT_TRAININGS_FETCHING"
export const GET_BOT_TRAININGS_FETCH = "GET_BOT_TRAININGS_FETCH"
export const GET_BOT_TRAININGS_FETCH_ERROR = "GET_BOT_TRAININGS_FETCH_ERROR"
