// updater
export const DO_UPDATE_FETCHING = 'DO_UPDATE_FETCHING'
export const DO_UPDATE_FETCH = 'DO_UPDATE_FETCH'
export const DO_UPDATE_FETCH_ERROR = 'DO_UPDATE_FETCH_ERROR'
// updater
export const CHECKER_UPDATE_FETCHING = 'CHECKER_UPDATE_FETCHING'
export const CHECKER_UPDATE_FETCH = 'CHECKER_UPDATE_FETCH'
export const CHECKER_UPDATE_FETCH_ERROR = 'CHECKER_UPDATE_FETCH_ERROR'
// reset global
export const RESET_GLOBAL = 'RESET_GLOBAL'
