//Set Seller
export const SET_SEARCH_SELLER_FETCHING = 'SET_SEARCH_SELLER_FETCHING'
export const SET_SEARCH_SELLER_FETCH = 'SET_SEARCH_SELLER_FETCH'
export const SET_SEARCH_SELLER_FETCH_ERROR = 'SET_SEARCH_SELLER_FETCH_ERROR'
//Set Clients
export const SET_SEARCH_CLIENTS_FETCHING = 'SET_SEARCH_CLIENTS_FETCHING'
export const SET_SEARCH_CLIENTS_FETCH = 'SET_SEARCH_CLIENTS_FETCH'
export const SET_SEARCH_CLIENTS_FETCH_ERROR = 'SET_SEARCH_CLIENTS_FETCH_ERROR'
// Reset Search
export const RESET_SEARCH = 'RESET_SEARCH'
