export const GET_CLIENTS_FETCHING = 'GET_CLIENTS_FETCHING'
export const GET_CLIENTS_FETCH = 'GET_CLIENTS_FETCH'
export const GET_CLIENTS_FETCH_ERROR = 'GET_CLIENTS_FETCH_ERROR'

export const GET_CLIENT_FETCHING = 'GET_CLIENT_FETCHING'
export const GET_CLIENT_FETCH = 'GET_CLIENT_FETCH'
export const GET_CLIENT_FETCH_ERROR = 'GET_CLIENT_FETCH_ERROR'

export const CREATE_CLIENT_FETCHING = 'CREATE_CLIENT_FETCHING'
export const CREATE_CLIENT_FETCH = 'CREATE_CLIENT_FETCH'
export const CREATE_CLIENT_FETCH_ERROR = 'CREATE_CLIENT_FETCH_ERROR'

export const DELETE_CLIENT_FETCHING = 'DELETE_CLIENT_FETCHING'
export const DELETE_CLIENT_FETCH = 'DELETE_CLIENT_FETCH'
export const DELETE_CLIENT_FETCH_ERROR = 'DELETE_CLIENT_FETCH_ERROR'

export const EDIT_CLIENT_FETCHING = 'EDIT_CLIENT_FETCHING'
export const EDIT_CLIENT_FETCH = 'EDIT_CLIENT_FETCH'
export const EDIT_CLIENT_FETCH_ERROR = 'EDIT_CLIENT_FETCH_ERROR'

export const GET_CLIENTS_BY_USER_ID_FETCHING = 'GET_CLIENTS_BY_USER_ID_FETCHING'
export const GET_CLIENTS_BY_USER_ID_FETCH = 'GET_CLIENTS_BY_USER_ID_FETCH'
export const GET_CLIENTS_BY_USER_ID_FETCH_ERROR = 'GET_CLIENTS_BY_USER_ID_FETCH_ERROR'