// Login
export const LOGIN_FETCHING = 'LOGIN_FETCHING'
export const LOGIN_FETCH = 'LOGIN_FETCH'
export const LOGIN_FETCH_ERROR = 'LOGIN_FETCH_ERROR'
// Logout
export const LOGOUT = 'LOGOUT'
// RESTORE PASSWORD
export const RESTORE_PASS_FETCHING = 'RESTORE_PASS_FETCHING'
export const RESTORE_PASS_FETCH = 'RESTORE_PASS_FETCH'
export const RESTORE_PASS_FETCH_ERROR = 'RESTORE_PASS_FETCH_ERROR'

export const RESTORE_PASS_VALIDATED_FETCHING = 'RESTORE_PASS_VALIDATED_FETCHING'
export const RESTORE_PASS_VALIDATED_FETCH = 'RESTORE_PASS_VALIDATED_FETCH'
export const RESTORE_PASS_VALIDATED_FETCH_ERROR =
  'RESTORE_PASS_VALIDATED_FETCH_ERROR'
// Auth token
export const AUTH_USER_BY_TOKEN_FETCHING = 'AUTH_USER_BY_TOKEN_FETCHING'
export const AUTH_USER_BY_TOKEN_FETCH = 'AUTH_USER_BY_TOKEN_FETCH'
export const AUTH_USER_BY_TOKEN_FETCH_ERROR = 'AUTH_USER_BY_TOKEN_FETCH_ERROR'



